// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeXg_h78XdSEvG5iTdohsoxUl9QFHrVfw',
    appId: '1:379061863915:web:6591468e6b31f3505745ae',
    messagingSenderId: '379061863915',
    projectId: 'video-call-app-a3be4',
    authDomain: 'video-call-app-a3be4.firebaseapp.com',
    storageBucket: 'video-call-app-a3be4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNNZ3u3aUbGdLaScKDgJwFJddsj6tpbU',
    appId: '1:379061863915:android:df45dda2f85a671e5745ae',
    messagingSenderId: '379061863915',
    projectId: 'video-call-app-a3be4',
    storageBucket: 'video-call-app-a3be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEGqtWB_qlBbIl-YX4NHvj7TiU0FhX20',
    appId: '1:379061863915:ios:220ab64eeb340b7e5745ae',
    messagingSenderId: '379061863915',
    projectId: 'video-call-app-a3be4',
    storageBucket: 'video-call-app-a3be4.appspot.com',
    androidClientId: '379061863915-ac166pn654peg7h5mjt0cng87vhm2giv.apps.googleusercontent.com',
    iosClientId: '379061863915-o10bahn5n29brqginv9i6q2f1it11667.apps.googleusercontent.com',
    iosBundleId: 'com.video.roberrt.videoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEGqtWB_qlBbIl-YX4NHvj7TiU0FhX20',
    appId: '1:379061863915:ios:220ab64eeb340b7e5745ae',
    messagingSenderId: '379061863915',
    projectId: 'video-call-app-a3be4',
    storageBucket: 'video-call-app-a3be4.appspot.com',
    androidClientId: '379061863915-ac166pn654peg7h5mjt0cng87vhm2giv.apps.googleusercontent.com',
    iosClientId: '379061863915-o10bahn5n29brqginv9i6q2f1it11667.apps.googleusercontent.com',
    iosBundleId: 'com.video.roberrt.videoApp',
  );
}
